apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: creator-api-hpa
  namespace: homolog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: creator-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue # <--- Uses absolute value, not percentage
          averageValue: 1000m # Scale if average usage > 1 cores
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max